# Generated by Django 4.2.16 on 2024-10-02 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Etape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("duree", models.IntegerField(default=0)),
                (
                    "etape_suivante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="high_level.etape",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Local",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("surface", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("prix", models.IntegerField(default=1)),
                ("n_serie", models.CharField(default="A", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Objet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(default="truc", max_length=200)),
                ("prix", models.IntegerField(default=400)),
            ],
        ),
        migrations.CreateModel(
            name="QuantiteRessource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Ville",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("code_postal", models.IntegerField(default=31400)),
                ("prixm2", models.IntegerField(default=400)),
            ],
        ),
        migrations.CreateModel(
            name="Ressource",
            fields=[
                (
                    "objet_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="high_level.objet",
                    ),
                ),
            ],
            bases=("high_level.objet",),
        ),
        migrations.CreateModel(
            name="Siege",
            fields=[
                (
                    "local_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="high_level.local",
                    ),
                ),
            ],
            bases=("high_level.local",),
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.IntegerField(default=0)),
                (
                    "premiere_etape",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="high_level.etape",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="local",
            name="ville",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="high_level.ville"
            ),
        ),
        migrations.AddField(
            model_name="etape",
            name="machine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="high_level.machine"
            ),
        ),
        migrations.AddField(
            model_name="etape",
            name="ressources",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="high_level.quantiteressource",
            ),
        ),
        migrations.CreateModel(
            name="Usine",
            fields=[
                (
                    "local_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="high_level.local",
                    ),
                ),
                ("machines", models.ManyToManyField(to="high_level.machine")),
            ],
            bases=("high_level.local",),
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.IntegerField(default=0)),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="high_level.local",
                    ),
                ),
                (
                    "ressource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="high_level.ressource",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="quantiteressource",
            name="ressource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="high_level.ressource"
            ),
        ),
    ]
