# Generated by Django 4.2.16 on 2024-09-25 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Local",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("surface", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("prix", models.IntegerField(default=1)),
                ("n_serie", models.CharField(default="A", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Ville",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("code_postal", models.IntegerField(default=31400)),
                ("prixm2", models.IntegerField(default=400)),
            ],
        ),
        migrations.CreateModel(
            name="Siege",
            fields=[
                (
                    "local_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="high_level.local",
                    ),
                ),
            ],
            bases=("high_level.local",),
        ),
        migrations.AddField(
            model_name="local",
            name="ville",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="high_level.ville"
            ),
        ),
        migrations.CreateModel(
            name="Usine",
            fields=[
                (
                    "local_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="high_level.local",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="high_level.machine",
                    ),
                ),
            ],
            bases=("high_level.local",),
        ),
    ]
