# Generated by Django 4.2.16 on 2024-09-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("high_level", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usine",
            name="machine",
        ),
        migrations.AddField(
            model_name="usine",
            name="machines",
            field=models.ManyToManyField(to="high_level.machine"),
        ),
    ]
