# Generated by Django 4.2.16 on 2024-10-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("high_level", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="local",
            name="surface",
            field=models.IntegerField(default=200),
        ),
    ]
