# Generated by Django 4.2.16 on 2024-10-01 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("high_level", "0002_remove_usine_machine_usine_machines"),
    ]

    operations = [
        migrations.CreateModel(
            name="Etape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("duree", models.IntegerField(default=0)),
                (
                    "etape_suivante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="high_level.etape",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="high_level.machine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Objet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(default="truc", max_length=200)),
                ("prix", models.IntegerField(default=400)),
            ],
        ),
        migrations.CreateModel(
            name="QuantiteRessource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Ressource",
            fields=[
                (
                    "objet_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="high_level.objet",
                    ),
                ),
            ],
            bases=("high_level.objet",),
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.IntegerField(default=0)),
                (
                    "premiere_etape",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="high_level.etape",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="etape",
            name="ressources",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="high_level.quantiteressource",
            ),
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.IntegerField(default=0)),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="high_level.local",
                    ),
                ),
                ("ressource", models.ManyToManyField(to="high_level.ressource")),
            ],
        ),
        migrations.AddField(
            model_name="quantiteressource",
            name="ressource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="high_level.ressource"
            ),
        ),
    ]
